name: .NET 8.0

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore
      run: dotnet restore RhoLoader/RhoLoader.csproj

    - name: Build
      run: dotnet build -c Release RhoLoader/RhoLoader.csproj

    - name: Publish
      run: dotnet publish -c Release RhoLoader/RhoLoader.csproj

    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RhoLoader
        path: RhoLoader/bin/Release/net8.0-windows/win-x64/
